# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  - ps: |
          $ErrorActionPreference = "Stop"
          Invoke-WebRequest http://raw.githubusercontent.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
          Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary -> DESCRIPTION
  - C:\Program Files\Pandoc\ -> DESCRIPTION

# Adapt as necessary starting from here

# Install Pandoc
# source: https://github.com/krlmlr/r-appveyor/issues/82#issuecomment-261695154
before_test:
  - ps: >-
      if (-Not (Test-Path "C:\Program Files\Pandoc\")) {
        cinst --no-progress pandoc
      }
#  - ps: choco install pandoc --version 1.19.1 --allow-downgrade
  - ps: $env:Path += ";C:\Program Files\Pandoc\"
  - pandoc -v

environment:
  global:
    # Do not skip tests with skip_on_cran()
    NOT_CRAN: true

    # Reduce build time by only using binary packages
    PKGTYPE: win.binary
    #USE_RTOOLS: true
    # Warning: May have to temporarily switch the above options if a minimum
    # required version of a package is not available as a binary

    # Allow remotes to update curl/git2r/pkgbuild by not relying on them
    R_REMOTES_STANDALONE: true

    # Perform incoming CRAN checks that don't require remote access
    _R_CHECK_CRAN_INCOMING_: TRUE
    _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE

  matrix:
  # 64-bit
  - R_VERSION: release
    platform: x64
    R_ARCH: x64

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
# Uncomment the line below to stall AppVeyor on failure for debugging
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
